#!/usr/bin/env ruby
# Writes one stub page per talk into talk/, from _data/talk_catalogue.yml.
#
# Jekyll can't do this by itself: a generator plugin in _plugins/ would be ignored,
# because the github-pages gem runs Jekyll in safe mode. So the stubs are real files
# in the repo, generated here. They hold no content of their own -- everything the
# page shows (title, description, abstract, series, post_slugs) is read back out of
# the catalogue by _layouts/talk.html, keyed on `talk`.
#
# Run it after adding or renaming a talk:  make talk-pages

require "yaml"
require "fileutils"

ROOT = File.expand_path("..", __dir__)
CATALOGUE = File.join(ROOT, "_data", "talk_catalogue.yml")
TALK_DIR = File.join(ROOT, "talk")

entries = YAML.load_file(CATALOGUE) || []
FileUtils.mkdir_p(TALK_DIR)

wanted = {}
entries.each do |entry|
  key = entry["key"].to_s
  next if key.empty?
  next if entry["page"] == false # a talk that shouldn't have a page yet

  wanted[key] = <<~PAGE
    ---
    # Generated by scripts/generate_talk_pages.rb -- do not edit.
    # Everything about this talk lives in _data/talk_catalogue.yml.
    layout: talk
    permalink: /talk/#{key}/
    talk: #{key}
    title: #{entry["title"].to_s.inspect}
    ---
  PAGE
end

written = []
wanted.each do |key, body|
  path = File.join(TALK_DIR, "#{key}.md")
  next if File.exist?(path) && File.read(path) == body
  File.write(path, body)
  written << "#{key}.md"
end

# a talk that left the catalogue shouldn't leave its page behind
removed = []
Dir.glob(File.join(TALK_DIR, "*.md")).each do |path|
  key = File.basename(path, ".md")
  next if wanted.key?(key)
  File.delete(path)
  removed << "#{key}.md"
end

puts "talk pages: #{wanted.size} in the catalogue"
puts "  written: #{written.empty? ? "none (all up to date)" : written.join(", ")}"
puts "  removed: #{removed.join(", ")}" unless removed.empty?
